preload = __HOME__/Pictures/Background/kame-house-dragon-5120x2880-25003.jpg
wallpaper = eDP-1,__HOME__/Pictures/Background/kame-house-dragon-5120x2880-25003.jpg
wallpaper = HDMI-A-3,__HOME__/Pictures/Background/kame-house-dragon-5120x2880-25003.jpg
splash = false
ipc = on
