general {
    disable_loading_bar = true
    hide_cursor = false
}
background {
    monitor =
    path = __HOME__/Pictures/wallhaven-0jmz5w.jpg
    blur_passes = 2
    brightness = 0.8
    contrast = 1.1
}
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(ffffffff)
    font_size = 84
    font_family = Sans
    position = 0, 100
    halign = center
    valign = center
}
label {
    monitor =
    text = 输入密码解锁
    color = rgba(e6e6e6ff)
    font_size = 18
    font_family = Sans
    position = 0, 40
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 320, 54
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.15
    outer_color = rgba(7aa2f7ee)
    inner_color = rgba(1e1e2ecc)
    font_color = rgba(ffffffff)
    fade_on_empty = false
    placeholder_text = <i>输入密码...</i>
    hide_input = false
    check_color = rgba(9ece6aff)
    fail_color = rgba(f7768eff)
    fail_text = 身份验证失败
    position = 0, -60
    halign = center
    valign = center
}
